name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py37hf985489_1
  - argon2-cffi=21.1.0=py37h271585c_0
  - arrow-cpp=4.0.1=py37hf7c73f6_3
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - aws-c-common=0.4.57=hb1e8313_1
  - aws-c-event-stream=0.1.6=h23ab428_5
  - aws-checksums=0.1.9=hb1e8313_0
  - aws-sdk-cpp=1.8.185=he271ece_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - boost-cpp=1.73.0=h9ed2024_11
  - bottleneck=1.3.2=py37hf1fa96c_1
  - brotli=1.0.9=hb1e8313_2
  - brotlipy=0.7.0=py37h9ed2024_1003
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.17.1=h9ed2024_0
  - ca-certificates=2021.10.26=hecd8cb5_2
  - certifi=2021.10.8=py37hecd8cb5_0
  - cffi=1.14.6=py37h2125817_0
  - chardet=4.0.0=py37hecd8cb5_1003
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.11.0=py37hecd8cb5_0
  - conda-package-handling=1.7.3=py37h9ed2024_1
  - cryptography=35.0.0=py37h2fd3fbb_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=h18a8e69_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.1.5=haf313ee_1
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h23ab428_2
  - fastparquet=0.5.0=py37he3068b8_1
  - freetype=2.11.0=hd8bbffd_0
  - gettext=0.19.8.1=h1f1d5ed_1
  - gflags=2.2.2=h0a44026_0
  - giflib=5.2.1=haf1e3a3_0
  - glib=2.68.0=hdf23fa2_0
  - glog=0.5.0=h23ab428_0
  - grpc-cpp=1.26.0=h044775b_0
  - icu=58.2=h0a44026_3
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py37hf985489_0
  - intel-openmp=2021.3.0=hecd8cb5_3375
  - ipykernel=5.5.5=py37h85f7c60_0
  - ipython=7.29.0=py37h4c52d7d_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jedi=0.18.0=py37hf985489_2
  - jinja2=3.0.2=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h9ed2024_0
  - jsonschema=4.1.2=pyhd8ed1ab_0
  - jupyter=1.0.0=py37hf985489_6
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py37hf985489_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py37h23ab428_0
  - krb5=1.19.2=hcd88c3b_0
  - lcms2=2.12=hf1fd2bf_0
  - libboost=1.73.0=hd4c2dcd_11
  - libcurl=7.78.0=hb8e4fae_0
  - libcxx=12.0.0=h2f01273_0
  - libedit=3.1.20210714=h9ed2024_0
  - libev=4.33=h9ed2024_1
  - libevent=2.1.8=hddc9c9b_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libllvm11=11.1.0=h9b2ccf5_0
  - libnghttp2=1.41.0=h7580e61_2
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.11.2=hd9629dc_0
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.9.0=ha12b0ac_1
  - libthrift=0.13.0=h054ceb0_6
  - libtiff=4.2.0=h87d7836_0
  - libwebp=1.2.0=hacca55c_0
  - libwebp-base=1.2.0=h9ed2024_0
  - llvm-openmp=12.0.0=h0dcd299_1
  - llvmlite=0.37.0=py37he4411ff_1
  - lz4-c=1.9.3=h23ab428_1
  - markupsafe=2.0.1=py37h271585c_0
  - matplotlib=3.3.4=py37hecd8cb5_0
  - matplotlib-base=3.3.4=py37h8b3ea08_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py37h271585c_1004
  - mkl=2021.3.0=hecd8cb5_517
  - mkl-service=2.4.0=py37h9ed2024_0
  - mkl_fft=1.3.0=py37h4a7008c_2
  - mkl_random=1.2.2=py37hb2f4e1b_0
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.2.0=py37hf985489_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.4.5=pyha770c72_0
  - numba=0.54.1=py37hae1ba45_0
  - numexpr=2.7.3=py37h5873af2_1
  - numpy=1.20.3=py37h4b4dc7a_0
  - numpy-base=1.20.3=py37he0bd621_0
  - olefile=0.46=py37_0
  - openssl=1.1.1l=h9ed2024_0
  - orc=1.6.7=h001ef8f_2
  - packaging=21.2=pyhd8ed1ab_1
  - pandas=1.3.3=py37h5008ddb_0
  - pandoc=2.16=h0d85af4_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.2=py37hecd8cb5_0
  - pcre=8.45=h23ab428_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py37h98e4679_0
  - pip=21.2.2=py37hecd8cb5_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.21=pyha770c72_0
  - prompt_toolkit=3.0.21=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyarrow=4.0.1=py37hdf3e9eb_3
  - pycosat=0.6.3=py37h9ed2024_0
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h2a560b1_4
  - pyrsistent=0.17.3=py37h271585c_2
  - pysocks=1.7.1=py37hecd8cb5_0
  - python=3.7.9=h26836e1_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python.app=3=py37h9ed2024_0
  - python_abi=3.7=2_cp37m
  - pytz=2021.3=pyhd3eb1b0_0
  - pyzmq=22.2.1=py37h23ab428_1
  - qt=5.9.7=h468cd18_1
  - qtconsole=5.1.1=pyhd8ed1ab_0
  - qtpy=1.11.2=pyhd8ed1ab_0
  - re2=2020.11.01=h23ab428_1
  - readline=8.1=h9ed2024_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.100=py37h9ed2024_0
  - scikit-learn=0.24.1=py37hb2f4e1b_0
  - scipy=1.7.1=py37h88652d9_2
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py37hecd8cb5_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=hb1e8313_0
  - sqlite=3.36.0=hce871da_0
  - statsmodels=0.12.2=py37h9ed2024_0
  - tbb=2021.4.0=haf03e11_0
  - terminado=0.12.1=py37hf985489_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - thrift=0.11.0=py37h23ab428_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py37h9ed2024_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - tzdata=2021a=h52ac0ba_0
  - uriparser=0.9.3=h0a44026_1
  - urllib3=1.26.6=pyhd3eb1b0_1
  - utf8proc=2.6.1=h9ed2024_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py37hf985489_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.9=h322a384_0
  - pip:
    - cython==0.29.25
    - pystan==2.19.1.1
